services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      ["5432:5432"]
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: danhtam1168@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      ["8080:80"]
    depends_on:
      - db